In [1]:
import pandas as pd
from utils.requests_utils import *

In [2]:
data = inegi_denue_search_places(method='Buscar',
                                 key_word='restaurantes',
                                 latitude=19.430672,
                                 longitude=-99.196956,
                                 radio=1000)

In [3]:
df = pd.DataFrame(data)
print(df.shape)
df.head()

(327, 22)

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,CentroComercial,TipoCentroComercial,NumLocal
0,09016722511005663000000000U0,7444731,EUCAPA,EUCAPA,Restaurantes con servicio de preparación de al...,11 a 30 personas,CALLE,VIRGILIO,9,,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,,,Fijo,-99.19688009,19.43066968,,,
1,09016722511006483000000000U2,9137994,RESTAURANTE ATIPICO,ATIPICO,Restaurantes con servicio de preparación de al...,11 a 30 personas,CALLE,VIRGILIO,9,0,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,,,Fijo,-99.19707210,19.43055719,,,
2,09016722219007011011000000U0,762647,CONFETTI,GASTRONOMICA CONFETTI SA DE CV,Restaurantes con servicio de preparación de al...,0 a 5 personas,CALLE,VIRGILIO,9,0,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,,,Fijo,-99.19707210,19.43055719,,,
3,09016722511004731000000000U6,8646416,NAHNU,NAHNU,Restaurantes con servicio de preparación de al...,0 a 5 personas,CALLE,VIRGILIO,9,,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,,,Fijo,-99.19713141,19.43065205,,,
4,09016722511004963000000000U5,7983023,SUSHI BATTA,GERMIE ALIMENTOS SA DE CV,Restaurantes con servicio de preparación de al...,11 a 30 personas,CALLE,VIRGILIO,90,,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",5514515847,GERNICA@GMAIL.COM,WWW.SUSHIBATTA.COM,Fijo,-99.19676437,19.43056842,,,

In [4]:
df[df['Nombre'].str.lower().str.contains('sushi')]

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,CentroComercial,TipoCentroComercial,NumLocal
4,09016722511004963000000000U5,7983023,SUSHI BATTA,GERMIE ALIMENTOS SA DE CV,Restaurantes con servicio de preparación de al...,11 a 30 personas,CALLE,VIRGILIO,90,,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",5514515847,GERNICA@GMAIL.COM,WWW.SUSHIBATTA.COM,Fijo,-99.19676437,19.43056842,,,
27,09016722110001073000021918S7,762660,SUSHI ROLL,SUSHI ROLL SA DE CV,Restaurantes con servicio de preparación de al...,11 a 30 personas,CALLE,OSCAR WILDE,20,0,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,,,Fijo,-99.19756372,19.43112533,,,
38,09016722511005193000045349S8,8596056,SUSHI ITTO,SUSHI ITTO MEXICO S DE RL DE CV,Restaurantes con servicio de preparación de al...,11 a 30 personas,AVENIDA,EMILIO CASTELAR,121,,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,,WWW.SUSHI-ITTO.COM,Fijo,-99.19746118,19.42998434,,,
58,09016722110004093000028189M2,6794375,MR SUSHI MASARYK,RENTASU MEXICANA SA DE CV,Restaurantes con servicio de preparación de al...,11 a 30 personas,AVENIDA,PRESIDENTE MASARYK,354,0,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,MAZARIK@MRSUSHI.COM.MX,WWW.MRSUSHI.COM.MX,Fijo,-99.19636363,19.43158858,,,
133,09016722110001133000000000U9,763073,PUBBELLY SUSHI,SASORI PUBELLY LATINO SA DE CV,Restaurantes con servicio de preparación de al...,101 a 250 personas,AVENIDA,Presidente Masaryk,275,0,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,,,Fijo,-99.19217587,19.43154540,,,
223,09016722511002063001000000U6,689881,SUSHI BAR TEPANYAKI,GASTRONOMICA TAKENOYA SA DE CV,Restaurantes con servicio de preparación de al...,6 a 10 personas,PROLONGACION,MOLIERE,313,,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,ADMTAKE@GMAIL.COM,WWW.TAKENOYA.COM.MX,Fijo,-99.20098923,19.43712274,,,
234,09016722511000443000000000U2,737529,SUSHITO,VIEJO RINCON DE COYOACAN SA DE CV,Restaurantes con servicio de preparación de al...,11 a 30 personas,CALLE,ISAAC NEWTON,136,,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",5555316272,,,Fijo,-99.18925144,19.43306195,,,

In [5]:
df[(df['Nombre'].str.lower().str.contains('mandolina')) | (df['Razon_social'].str.lower().str.contains('mandolina'))]

Empty DataFrame
Columns: [CLEE, Id, Nombre, Razon_social, Clase_actividad, Estrato, Tipo_vialidad, Calle, Num_Exterior, Num_Interior, Colonia, CP, Ubicacion, Telefono, Correo_e, Sitio_internet, Tipo, Longitud, Latitud, CentroComercial, TipoCentroComercial, NumLocal]
Index: []

[0 rows x 22 columns]

In [6]:
df[(df['Nombre'].str.lower().str.contains('japo')) | (df['Razon_social'].str.lower().str.contains('japo'))]

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,CentroComercial,TipoCentroComercial,NumLocal
104,09016722511007315000000000U5,9348127,ROSANEGRA,TORAJAPONES SA DE CV,Restaurantes con servicio de preparación de al...,51 a 100 personas,AVENIDA,PRESIDENTE MASARYK,298,,...,"MIGUEL HIDALGO, Miguel Hidalgo, CIUDAD DE MÉXICO",,,WWW.ROSANEGRA..COM.MX,Fijo,-99.19341365,19.43140867,,,

In [7]:
df[(df['Nombre'].str.lower().str.contains('japo')) | (df['Razon_social'].str.lower().str.contains('japo'))]['Clase_actividad']

104    Restaurantes con servicio de preparación de al...
Name: Clase_actividad, dtype: object

In [10]:
data = inegi_denue_search_places(method='Cuantificar',
                                 economic_activity=71,
                                 geo_area='01',
                                 estrato=0)

# df = pd.DataFrame(data)
# print(df.shape)
# df.head()

In [11]:
data

[{'AE': '71', 'AG': '01', 'Total': '767'}]